name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - main
      - 'releases/*'

permissions: {}

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: 24
    - run: npm ci
    - run: npm test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: 24
    - run: npm ci
    - run: npm run prepare
    - uses: ./
      with:
        masks: SECRET1, SECRET2
        required: DIRENV_ACTION_TEST
        direnvVersion: 2.32.3
    - run: printenv | grep DIRENV_ACTION_TEST
    - run: echo $PATH | grep $(pwd)/bin
    - run: printenv

  test-default-option:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: 24
    - run: npm ci
    - run: npm run prepare
    - uses: ./
    - run: printenv | grep DIRENV_ACTION_TEST
    - run: echo $PATH | grep $(pwd)/bin
    - run: printenv
